language: php
php:
  - 7.2
  
services:
  - docker

env:
  COMPOSE_VERSION: 1.24.1

before_install:
  - cp .env.example .env
  # Docker Compose Install 
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose build
  - docker-compose up -d

before_script:
  - docker-compose exec app php artisan config:clear
  - docker-compose exec app php artisan migrate:refresh
  - docker-compose exec app php artisan db:seed

script:
  - docker-compose exec app php artisan dusk
